import { Krona_One } from 'next/font/google'
import './globals.css';
// Load the Krona One font with weight 400
const kronaOne = Krona_One({
  weight: '400',  // Specify the available weight
  subsets: ['latin'],
  display: 'swap',
});

export const metadata = {
  title: "Cine Dev Portfolio",
  description: "Generated by my mind",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${kronaOne.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}

